# syntax=docker/dockerfile:1

# ----- build stage -----
FROM maven:3.9.9-eclipse-temurin-21 AS builder
WORKDIR /workspace
COPY pom.xml .
COPY src ./src
RUN mvn -q -DskipTests clean package

# ----- runtime stage -----
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=builder /workspace/target/eureka-server-0.0.1-SNAPSHOT.jar app.jar
EXPOSE 8761
ENTRYPOINT ["java","-jar","/app/app.jar"]
